server:
  port: 80 
spring:
  application:
    name: dubbo-gateway 
dubbo:
  application:
    name: dubbo-gateway 
    id:  dubbo-gateway 
  protocol:
    id: dubbo
    name: dubbo
    port: 12345
  registry:
    address: zookeeper://123.206.72.111:2181
  #scan:
   # base-packages:
      #-com.gre.sys.modules.test.service  
